// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-project-api/internal/storage (interfaces: RepoStorage,ProjectStorage)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ozoncp/ocp-project-api/internal/models"
)

// MockRepoStorage is a mock of RepoStorage interface.
type MockRepoStorage struct {
	ctrl     *gomock.Controller
	recorder *MockRepoStorageMockRecorder
}

// MockRepoStorageMockRecorder is the mock recorder for MockRepoStorage.
type MockRepoStorageMockRecorder struct {
	mock *MockRepoStorage
}

// NewMockRepoStorage creates a new mock instance.
func NewMockRepoStorage(ctrl *gomock.Controller) *MockRepoStorage {
	mock := &MockRepoStorage{ctrl: ctrl}
	mock.recorder = &MockRepoStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoStorage) EXPECT() *MockRepoStorageMockRecorder {
	return m.recorder
}

// AddRepo mocks base method.
func (m *MockRepoStorage) AddRepo(arg0 context.Context, arg1 models.Repo) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRepo", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRepo indicates an expected call of AddRepo.
func (mr *MockRepoStorageMockRecorder) AddRepo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRepo", reflect.TypeOf((*MockRepoStorage)(nil).AddRepo), arg0, arg1)
}

// DescribeRepo mocks base method.
func (m *MockRepoStorage) DescribeRepo(arg0 context.Context, arg1 uint64) (*models.Repo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeRepo", arg0, arg1)
	ret0, _ := ret[0].(*models.Repo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeRepo indicates an expected call of DescribeRepo.
func (mr *MockRepoStorageMockRecorder) DescribeRepo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeRepo", reflect.TypeOf((*MockRepoStorage)(nil).DescribeRepo), arg0, arg1)
}

// ListRepos mocks base method.
func (m *MockRepoStorage) ListRepos(arg0 context.Context, arg1, arg2 uint64) ([]models.Repo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepos", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Repo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepos indicates an expected call of ListRepos.
func (mr *MockRepoStorageMockRecorder) ListRepos(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepos", reflect.TypeOf((*MockRepoStorage)(nil).ListRepos), arg0, arg1, arg2)
}

// MultiAddRepo mocks base method.
func (m *MockRepoStorage) MultiAddRepo(arg0 context.Context, arg1 []models.Repo) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiAddRepo", arg0, arg1)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MultiAddRepo indicates an expected call of MultiAddRepo.
func (mr *MockRepoStorageMockRecorder) MultiAddRepo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiAddRepo", reflect.TypeOf((*MockRepoStorage)(nil).MultiAddRepo), arg0, arg1)
}

// RemoveRepo mocks base method.
func (m *MockRepoStorage) RemoveRepo(arg0 context.Context, arg1 uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRepo", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveRepo indicates an expected call of RemoveRepo.
func (mr *MockRepoStorageMockRecorder) RemoveRepo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRepo", reflect.TypeOf((*MockRepoStorage)(nil).RemoveRepo), arg0, arg1)
}

// UpdateRepo mocks base method.
func (m *MockRepoStorage) UpdateRepo(arg0 context.Context, arg1 models.Repo) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepo", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRepo indicates an expected call of UpdateRepo.
func (mr *MockRepoStorageMockRecorder) UpdateRepo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepo", reflect.TypeOf((*MockRepoStorage)(nil).UpdateRepo), arg0, arg1)
}

// MockProjectStorage is a mock of ProjectStorage interface.
type MockProjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockProjectStorageMockRecorder
}

// MockProjectStorageMockRecorder is the mock recorder for MockProjectStorage.
type MockProjectStorageMockRecorder struct {
	mock *MockProjectStorage
}

// NewMockProjectStorage creates a new mock instance.
func NewMockProjectStorage(ctrl *gomock.Controller) *MockProjectStorage {
	mock := &MockProjectStorage{ctrl: ctrl}
	mock.recorder = &MockProjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectStorage) EXPECT() *MockProjectStorageMockRecorder {
	return m.recorder
}

// AddProject mocks base method.
func (m *MockProjectStorage) AddProject(arg0 context.Context, arg1 models.Project) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProject", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProject indicates an expected call of AddProject.
func (mr *MockProjectStorageMockRecorder) AddProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProject", reflect.TypeOf((*MockProjectStorage)(nil).AddProject), arg0, arg1)
}

// DescribeProject mocks base method.
func (m *MockProjectStorage) DescribeProject(arg0 context.Context, arg1 uint64) (*models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeProject", arg0, arg1)
	ret0, _ := ret[0].(*models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeProject indicates an expected call of DescribeProject.
func (mr *MockProjectStorageMockRecorder) DescribeProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeProject", reflect.TypeOf((*MockProjectStorage)(nil).DescribeProject), arg0, arg1)
}

// ListProjects mocks base method.
func (m *MockProjectStorage) ListProjects(arg0 context.Context, arg1, arg2 uint64) ([]models.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockProjectStorageMockRecorder) ListProjects(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockProjectStorage)(nil).ListProjects), arg0, arg1, arg2)
}

// MultiAddProject mocks base method.
func (m *MockProjectStorage) MultiAddProject(arg0 context.Context, arg1 []models.Project) ([]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiAddProject", arg0, arg1)
	ret0, _ := ret[0].([]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MultiAddProject indicates an expected call of MultiAddProject.
func (mr *MockProjectStorageMockRecorder) MultiAddProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiAddProject", reflect.TypeOf((*MockProjectStorage)(nil).MultiAddProject), arg0, arg1)
}

// RemoveProject mocks base method.
func (m *MockProjectStorage) RemoveProject(arg0 context.Context, arg1 uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveProject", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveProject indicates an expected call of RemoveProject.
func (mr *MockProjectStorageMockRecorder) RemoveProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProject", reflect.TypeOf((*MockProjectStorage)(nil).RemoveProject), arg0, arg1)
}

// UpdateProject mocks base method.
func (m *MockProjectStorage) UpdateProject(arg0 context.Context, arg1 models.Project) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockProjectStorageMockRecorder) UpdateProject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockProjectStorage)(nil).UpdateProject), arg0, arg1)
}
