// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-project-api/internal/storage (interfaces: Storage)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ozoncp/ocp-project-api/internal/models"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddObjects mocks base method.
func (m *MockStorage) AddObjects(arg0 []models.Artifact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddObjects", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddObjects indicates an expected call of AddObjects.
func (mr *MockStorageMockRecorder) AddObjects(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddObjects", reflect.TypeOf((*MockStorage)(nil).AddObjects), arg0)
}

// DescribeObject mocks base method.
func (m *MockStorage) DescribeObject(arg0 uint64) (*models.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeObject", arg0)
	ret0, _ := ret[0].(*models.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeObject indicates an expected call of DescribeObject.
func (mr *MockStorageMockRecorder) DescribeObject(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeObject", reflect.TypeOf((*MockStorage)(nil).DescribeObject), arg0)
}

// ListObject mocks base method.
func (m *MockStorage) ListObject(arg0, arg1 uint64) ([]models.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObject", arg0, arg1)
	ret0, _ := ret[0].([]models.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObject indicates an expected call of ListObject.
func (mr *MockStorageMockRecorder) ListObject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObject", reflect.TypeOf((*MockStorage)(nil).ListObject), arg0, arg1)
}

// RemoveObject mocks base method.
func (m *MockStorage) RemoveObject(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObject", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveObject indicates an expected call of RemoveObject.
func (mr *MockStorageMockRecorder) RemoveObject(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObject", reflect.TypeOf((*MockStorage)(nil).RemoveObject), arg0)
}
