service:
    host: 0.0.0.0
    grpc_port: 8084
    http_port: 8080
storage:
    driver: postgres
    user: lobanov
    db_name: ocp
    ssl_mode: disable
kafka:
    brokers:
        - 127.0.0.1:9094
    events_topic: events
    ping_topic: ping
    capacity: 256
metrics:
    host: 0.0.0.0
    port: 9101
