name: Build and test

on:
  push:
    branches: [ main, homework*, feature/* ]
  pull_request:
    branches: [ main ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add tag
      run: git tag v0.0.0 

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make tests
